# VTM - Workflow
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14.x
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test
